### ISSUE TITLE
Sass instructions do not explain how to import the module

### ISSUE THREAD

**Issue by nickcolley** [Financial-Times/o-lazy-load#32]
https://github.com/Financial-Times/o-lazy-load#sass

```
SassError: Undefined mixin.
       ╷
    51 │ @include oLazyLoad();
       │ ^^^^^^^^^^^^^^^^^^^^
       ╵
```

In `next-article` there is this convention:

```scss
$o-lazy-load-is-silent: false;
@import 'o-lazy-load/main';
```

**Comment by JakeChampion** [comment]
Thank you for this issue @nickcolley, it is a really good point.

We should likely have a page on origami.ft.com which we link to from every component's readme.md file about how to import and instantiate the JS and the Sass/CSS.

**Comment by notlee** [comment]
Plus one your suggestion @JakeChampion. I created a new issue for this as it would affect each component: https://github.com/Financial-Times/origami/issues/59

What do you think? Happy for me to close this issue for that?

**Comment by notlee** [comment]
I'm going to take silence as a yes. Let me know if you think the new issue doesn't cover it :)

**Comment by nickcolley** [comment]
@notlee sorry, that's excellent thank you!
